import "./globals.css";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Header } from "./components/Header";

const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "OSINT Terminal",
  description: "Generated by VibecodeKit — osint-terminal preset",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const hasToken = process.env.HAS_TOKEN === "1";
  return (
    <html lang="en" className={mono.variable}>
      <body className="min-h-screen">
        <Header hasToken={hasToken} />
        <main className="mx-auto max-w-7xl px-6 pb-16 pt-24">{children}</main>
        <footer className="border-t border-border bg-panel/50 px-6 py-4 text-[10px] uppercase tracking-widest text-text-muted">
          <div className="mx-auto flex max-w-7xl items-center justify-between">
            <span className="ascii-bracket">node // local</span>
            <span>VibecodeKit · osint-terminal preset</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
